### ISSUE TITLE
GP Premium

### ISSUE THREAD

**Issue by mmjaeger** [tomusborne/generatepress#32]
I think that many users would welcome some breadcrumb functionality so we don't have to install another plugin?

Thanks

**Comment by tomusborne** [comment]
I've considered it before, but it seems like most people use Yoast SEO which has breadcrumbs (done really well). Perhaps a super light/simple breadcrumb element could be added.

**Comment by mmjaeger** [comment]
I try to avoid to install another plugin just for the breadcrumbs - a light breadcrumb feature would be great

**Comment by westsyde** [comment]
Excuse my rant.. lol.. If only Yoast SEO was just another plugin.. Its potentially the single most important plugin the WordPress repository.. Its well worth utilising for a number of reasons.. Maybe you're an SEO guru and know everything about it.. If not or if SEO isn't important to you I fail to see the point in breadcrumbs.. My vote is to keep the theme as light as possible and let popular plugins provide the functionality they were intended to provide.. No one does an SEO like Yoast.. I've used many alternatives and after a few years of doing that I now pay for Yoast premium because there is no better option..

**Comment by mmjaeger** [comment]
@westsyde breadcrumbs is not only for SEO but also for navigating, isn't it

**Comment by westsyde** [comment]
@mmjaeger Of course though if site SEO is rank and no one goes to the site or less than optimum traffic SEO factor is of primary importance is it not.. From your reply I take it you're no SEO guru so my suggestion is to use Yoast. I too don't use plugins I don't need.. SEO shouldn't be on the exclusions list.
