### ISSUE TITLE
GP Premium

### ISSUE THREAD

**Issue by mmjaeger** [tomusborne/generatepress#40]
trying to update gp premium in WP and I'm always getting an error:

Downloading update from https://generatepress.com/edd-sl/package_download/MTUxMTg3OTM1NDo5ZmVkNDM2ODdiMmUyMTdiOWY3OTcyODAyYjM4ZDA1ZDoyNTQ0MTo4YTMxZmI0MmFjMGVlY2ExMWZhMjg4N2UwYTIwODE2YTpodHRwQC8vdGVycmFzb2x1dGlvbnMuY29tOjA=…
An error occurred while updating GP Premium: Download failed. Unauthorized

**Comment by generatepress** [comment]
Hi there,

This should help: https://docs.generatepress.com/article/updating-issues/#getting-an-unauthorized-message


Leo HsiangCustomer Support

--- original message ---
On Mon, Nov 27, 2017 at 02:32 pm, <notifications@github.com> mmjaeger wrote:


trying to update gp premium in WP and I'm always getting an error:

Downloading update from https://generatepress.com/edd-sl/package_download/MTUxMTg3OTM1NDo5ZmVkNDM2ODdiMmUyMTdiOWY3OTcyODAyYjM4ZDA1ZDoyNTQ0MTo4YTMxZmI0MmFjMGVlY2ExMWZhMjg4N2UwYTIwODE2YTpodHRwQC8vdGVycmFzb2x1dGlvbnMuY29tOjA=…

An error occurred while updating GP Premium: Download failed. Unauthorized

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
