### ISSUE TITLE
Back to Top - Double tap links on Chrome iOS

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#407]
### Description
We have had a couple of instances reporting that content links require double tapping on Chrome iOS.
And that this behaviour stops when the Back to Top is disabled.

### Steps to reproduce
See support topic example here:

https://generatepress.com/forums/topic/chrome-ios-double-tap-issue-when-using-back-to-top-button/#post-2271108

Chrome mobile is a pain to debug, more so on iOS.
But there seems to be evidence of a conflict here.
Might be worth us reviewing the back to top script.

**Comment by klegall** [comment]
Thanks for creating this, David! It would be great to fix it as the issue has a direct impact on bounce rate.

**Comment by tomusborne** [comment]
I'm not able to reproduce this on my iPhone using Chrome.

Sometimes the actual back to top button requires a second click (due to its hover state I believe), but the back to top script shouldn't affect regular links, as the script is only listening to clicks on the back to top button itself.

**Comment by GoldenGoldy** [comment]
Thanks for looking into this!
I just tested again though and I continue to be able to reproduce the issue using the steps described here: https://generatepress.com/forums/topic/chrome-ios-double-tap-issue-when-using-back-to-top-button/#post-2271108 (using the staging site for which the url was provided in the private info with that ticket)

I tested it on both an iPad and iPhone again and continue to have the issue, also with the links.
What I did now notice is the following though:
It's not always required to tap the links twice, it actually also works if you first tap anywhere else in the content area after you scroll down. If I scroll down to a position below the fold and I tap a link that was below the fold before scrolling, then I do have the issue. But if I scroll down to a position below the fold and I tap first anywhere else in the content area (just on some text for example), and after that I tap a link, then I don't have the issue.

It's almost like the content area (containing the links) needs to regain focus first before you can tap a link there.

I also confirmed again that when I disable the back to top button, the issue disappears. I understand your comment that in principle it shouldn't affect the regular links but perhaps in Chrome on IOS something strange happens that makes the content area lose focus because of the back to top button that pops into view after you scroll down?
