### ISSUE TITLE
Complying with GDPR - local fonts instead served by Google

### ISSUE THREAD

**Issue by masteradhoc** [tomusborne/generatepress#424]
### Description
Currently a lot GP Sites use fonts that are from google. So far so good.
There was quite some discussion in the WordPress Community lately to push theme authors to use locally served fonts instead over google.

Would be amazing if GP could help here natively and download the fonts choosen and serve them directly
FYI: https://make.wordpress.org/themes/2022/06/18/complying-with-gdpr-when-using-google-fonts/

**Comment by JeanPaiva** [comment]
Hello @masteradhoc we are aware of this discussions and we also have spoken with some folks from the themes team to check specific solutions for GeneratePress.

The current GP typography system allows you to manually download GFonts and use them locally. Also, we will be implementing this functionality via UI in the future.

Since GP is in the market for so long we have thousands of sites using our plugin so big change like these require us to think in backwards compatibility to avoid headaches for our users.

But we will be working towards having GeneratePress and all our products to be GDPR compliant. Thanks for your input.

Reference: https://docs.generatepress.com/article/adding-local-fonts/

**Comment by masteradhoc** [comment]
@JeanPaiva any update on this?
