### ISSUE TITLE
Full width containers overflow the viewport 

### ISSUE THREAD

**Issue by stacyk** [tomusborne/generatepress#470]
### Description
When using a full width container without a sidebar, the content in the container will overflow the left side of the page if scrollbars exist (I believe due to the use of 100vw in the calculation)

```
.no-sidebar .entry-content .alignfull {
    margin-left: calc( -100vw / 2 + 100% / 2);
    margin-right: calc( -100vw / 2 + 100% / 2);
    max-width: 100vw;
    width: auto;
}
```

Maybe it has something to do with how it is nested and I'm not sure if there are great solutions that wouldn't require javascript to detect scroll bars?

![Screen Shot 2022-11-04 at 3 22 03 PM](https://user-images.githubusercontent.com/1581694/200067465-a102bced-fed0-41f2-b8a8-67956770ee63.jpg)

**Comment by diggeddy** [comment]
There isn't much that can be done about this.
As there is no way to know that a sidebar is present on a page.
We don't recommend using the align Full / Wide settings because of this. 
Instead set the GP Content Container to Full Width:

https://docs.generatepress.com/article/content-container/

And built out from a Full width to begin with.
