### ISSUE TITLE
Media & Text block: alignfull and alignwide (with sidebar)

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#76]
I tested GP and the Text & Media Block. I noticed an error during this process:

Both `alignfull` and `alignwide` do the same. There is no difference here. I would expect that the option "with Sidebar" would hide the option `alignfull`. And with "without sidebar" the option `alignfull` is faded in. That would be more intuitive.

Not only in this block this would be interesting, but also for all others. I admit that this is a small detail, but it would be an added value.

**Comment by tomusborne** [comment]
Removing an option from Gutenberg would likely cause more confusion.

Instead, I think this is when it's good to make a decision for the user. Instead of forcing it to be full width with a sidebar (looks terrible), we just make it use the full width of the content area.

If it was up to me the `alignfull` option wouldn't exist. The way they suggest themes handle it is super hack-y.

**Comment by SchneiderSam** [comment]
Ok. Fine!
